=head1 NAME

Stream::Manual::Caps - stream capabilities

=head1 DESCRIPTION

See L<Stream::Base> documentation for basic explanation about what stream capabilities are.

To make use of caps, we need a common list of their names and meanings. See below for such list.

=head1 COMMON CAPABILITIES

=over

=item I<lag>

Input streams having this cap implement C<lag()> method, which return amount of data remaining in stream.

=item I<persistent>

If set for output stream, data written into it will be saved somewhere.

=item I<sorted>

If set for input stream, that stream is a sequence, i.e. it's sorted somehow. All streams from C<PPB::Join> family will have this cap soon.

=item I<size>

If set for storage, storage must implement C<size()> method returning storage size in bytes.

=cut

=back

=cut
